project_name: cf-security-entitlement

builds:
  -
    &template
    id: server
    binary: cfsecurity-server
    dir:  ./server
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  -
    <<: *template
    id: plugin
    binary: cfsecurity-plugin
    dir: ./plugin
  -
    <<: *template
    id: provider
    binary: terraform-provider-cfsecurity
    dir: ./terraform-provider-cfsecurity

archives:
  - id: archives
    builds:
      - server
      - plugin
      - provider
    format: "tar.gz"
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/*
      - assets/*
      - static/*
      - templates/*

  - id: plugin
    format: binary
    builds: [ plugin ]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

  - id: provider
    format: zip
    builds: [ provider ]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: orange-cloudfoundry
    name: cf-security-entitlement
  prerelease: auto
  name_template: '{{.Tag}}'
